# [jenkins]
# 172.31.17.147  ansible_ssh_user='ec2-user'

# [nginx]
# 172.31.56.255  ansible_ssh_user='ec2-user'

# [sonar]
# <Sonar-Private-IP-Address>

[artifactory]
172.31.28.237  ansible_ssh_user='ec2-user'


# [db]
# 172.31.50.212 ansible_ssh_user='ubuntu'